version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    depends_on:
      - mongo
volumes:
  mongo-data:
